import jp_ad_stage
import jp_ad
import jp_application_stage
import jp_application
import jp_candidate
import jp_agreement_stage
#import jp_employee
import jp_portal
import jp_trade
import jp_time_sheet
import jp_agreement
import jp_deal
import jp_publish
import jp_calculation
import jp_project
import wizard
import jp_sallary
import jp_report_recruitment
import report
import jp_deal_report
import jp_task_report_rec